name: SonarScanner
on:
  push:
    branches:
      ${github_default_branch} 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        fetch-depth: 0 #Disable shallow clones for better analysis relevancy
    - name: SonarQube Scan Generic
      uses: sonarsource/sonarqube-scan-action@069e3332cbefb8659c02d77b21a04719d3ef7c9b
      env:
        GITHUB_TOKEN: ${github_token}
        SONAR_TOKEN: ${sonar_token}
        SONAR_HOST_URL: ${sonar_host_url}
